### ISSUE TITLE
Test should halt on error page

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/UI-Testing-Toolbox#104]
When the site returns an ASP.Net Core error page the test should be failed without going further. Similarly to existing HTML validation. Currently if the site returns an error page it will fail on the following steps, becuase the elements that correspond to the selectors won't exist. This creates an opaque test failure message that doesn't indicate the actual problem making it harder to diagnose.

It should identify the error page, scrape the exception message and stack trace. and put that info into the test failure.

**Comment by Piedone** [comment]
Since we can't retrieve the HTTP code in Selenium, and you can override the error page, I don't think exactly this would be a viable solution.

What we could do is run the Orchard error log asserting logic after every page view (how we do it for HTML markup validation) instead of once at the end of the test. Similarly with the browser log. This would make tests with such errors fail much sooner.

What do you think?

**Comment by sarahelsaig** [comment]
Oh, I assumed it's possible to "un-override" the error page. But I like your idea better.

**Comment by Piedone** [comment]
Let's do the following here:

- Assert on both the Orchard logs and the browser logs on each page change (basically what happens in `AssertLogsAsync()`).
- Keep these assertions for the end of the test too because page change events are not foolproof, and a test doesn't necessarily invoke a page change.
- Note the caching logic in `GetBrowserLogAsync()`.
