### ISSUE TITLE
Broken Link on Readme Page

### ISSUE THREAD

**Issue by amons02** [Lombiq/UI-Testing-Toolbox#171]
The link in [this readme](https://github.com/Lombiq/UI-Testing-Toolbox/blob/c3214161ae6f4bfbaf056a7a8dae102c364be80b/Lombiq.Tests.UI.Samples/Readme.md#tutorial) under the second tutorial bullet point is broken. I believe it should now point to [this file](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/be20752a392f4cdd4715be3842196d3836aac8e7/src/Lombiq.OSOCE.Web/Program.cs).

**Comment by Piedone** [comment]
Good point, yes, though it should rather point to [this file](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/src/Lombiq.OSOCE.Web/Program.cs). And the wording also needs to be changed to reference the .NET 6 `Program` file instead of the `Startup` class.

Would you venture into submitting a pull request for this?

BTW I see you worked with computer vision and HDLs; [our Hastlayer project](https://github.com/Lombiq/Hastlayer-SDK) might be interesting for your :).

**Comment by amons02** [comment]
Sure, I can submit a PR. Hastlayer looks interesting, I'll have to look into it more :).

**Comment by Piedone** [comment]
Thank you!
