### ISSUE TITLE
Add images to failure dump that fail assertions, e.g. of dimensions (OSOE-497)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/UI-Testing-Toolbox#244]
When running [BasicVisualVerificationTests.VerifyNavbar()](https://github.com/Lombiq/UI-Testing-Toolbox/blob/d4e82bc8cea01d6f58d32370e73aa10c07ee4f07/Lombiq.Tests.UI.Samples/Tests/BasicVisualVerificationTests.cs#L58) all the while the `.navbar-brand` element has some missing or broken styles, the test will fail like this:

```
Error:
  Shouldly.ShouldAssertException : elementImageOriginal.Height
      should be greater than or equal to
  28
      but was
  18
```
See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3694863540, Annotations, 6th error for an example.

![image](https://user-images.githubusercontent.com/1976647/207736803-2ac32d61-60cd-4331-a98f-9dddb34ae839.png)

The above error is not very helpful in case you're not already deep inside the concerned area of code. It would be more helpful to have the offending element **screenshots**, the expected and the actual ones, **inside the failure dump** in order to more quickly and easily identify the problematic element on the page.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-497)

**Comment by 0liver** [comment]
Here's where the error is thrown on size mismatch: https://github.com/Lombiq/UI-Testing-Toolbox/blob/fb10e99ff04138c500902313f1c36ae0d26477f6/Lombiq.Tests.UI/Extensions/VisualVerificationUITestContextExtensions.cs#L405.

We could catch those potential exceptions, add the images to the failure dump, and then simply `throw` again. For example.

**Comment by Piedone** [comment]
The images are added to the failure dump. Under the _DebugInformation/VisualVerification_ folder, you should the following for each failing visual verification assertion: the baseline image, the actual image, and a mask of the diff between the two. There are further files for context too:

![image](https://user-images.githubusercontent.com/1976647/210408024-553dce4a-f088-4384-b832-aec09e4ea3ad.png)

What are you missing from these?

**Comment by 0liver** [comment]
Take a look at the code place linked above - there are Shouldly assertions that throw exceptions when not met, and no images are being saved to the dump.

**Comment by Piedone** [comment]
OK, so this is only for dimension mismatch.

**Comment by Piedone** [comment]
While images are not saved to the failure dump like above, the captured element image is saved to the failure dump (as well as full-page screenshots of the whole test, as usual). A diff can't be saved, because for that we need images of the same dimension.

So, what can be done is a better exception message that explains what the issue is and how to fix it. Does something like this sound more helpful?

> The dimensions of the captured element (264px x 28px) are smaller than the dimensions of the baseline image (270px x 29px). This can happen if due to a change in the app, the captured element got smaller than before, or if the baseline image is mistakenly too large. The suggested baseline image with a screenshot of the captured element was saved to the failure dump. Compare this with the original image used by the test and if suitable, use it as the baseline going forward.

**Comment by 0liver** [comment]
Surely, the proposed exception message is much better.

I was thinking that we could save screenshots of just the mismatched element - the page screenshot wasn't very helpful in finding the cause of the issue because it was just a the header text element that was slightly lower than expected which was (almost) not visible on the large screenshots.

**Comment by Piedone** [comment]
In such cases, the suggested file (i.e. that's a current screenshot of the tested element, with the correct dimensions) will be (already is) saved to the failure dump, like this:

![image](https://user-images.githubusercontent.com/1976647/210464457-d1c24b49-fa5c-406c-a5ea-aecee3aa13cf.png)

You can use this to compare the baseline image (i.e. that's saved in the repo to test against) that you have locally. But algorithmically this isn't straightforward, since the two files will have different dimensions (so, there's no way to diff them unless we assume a location of the smaller image on the larger one, like upper-left corner, which is arbitrary).
