### ISSUE TITLE
UI test crashes if the web project doesn't reference Lombiq.Tests.UI.Shortcuts (OSOE-626)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/UI-Testing-Toolbox#279]
Even if it's not yet used. It throws the exception:

``InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.ILookupNormalizer' while attempting to activate 'Microsoft.AspNetCore.Identity.RoleManager`1[OrchardCore.Security.IRole]'.``

This dependency should be optional, and UI tests should work without it if no shortcuts are actually used.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-626)

**Comment by DemeSzabolcs** [comment]
Referencing `Lombiq UI Testing Toolbox - Shortcuts` in the web project, **but** removing `OrchardCore.Users`, from the `Lombiq UI Testing Toolbox - Shortcuts`'s `Manifest.cs` results in the same error. So actually the lack of `OrchardCore.Users` causes the error. At least this is my first guess, but I will continue my research.

**Comment by DemeSzabolcs** [comment]
Huh strange. Turning on `OrchardCore.Users` in the web project's `Program.cs` with `.AddTenantFeatures("OrchardCore.Users")` also fixes the problem. However turning this feature on later in a recipe is too late, and results in the same error.

**Comment by DemeSzabolcs** [comment]
>Even if it's not yet used. It throws the exception.

Actually, it is used since it's enabled by default: https://github.com/Lombiq/UI-Testing-Toolbox/blob/f743ac88d0845b4072374d034104642acdd76543/Lombiq.Tests.UI/Services/OrchardCoreInstance.cs#L172

I will add a note about that, and fix the 
```InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.ILookupNormalizer' while attempting to activate 'Microsoft.AspNetCore.Identity.RoleManager`1[OrchardCore.Security.IRole]'.``` error. Since it is a somewhat false error and the app should work regardless, we should just get a 404 when we try to use Shortcuts url when the module is not referenced instead.
