### ISSUE TITLE
SignInDirectly randomly fails with 404 (OSOE-727)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/UI-Testing-Toolbox#321]
Seemingly randomly, `SignInDirectly` calls will fail, due to _1/Lombiq.Tests.UI.Shortcuts/Account/SignInDirectly?userName=admin_ failing with a 404. See e.g. [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/6833743931/attempts/1), [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/6842966216/attempts/1), and [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7036541596). In both cases, the NuGetTest solution build failed under Ubuntu and passed with a rerun. Since due to a rerun the failure dump is not available, I'm attaching one of the test's here:

[Lombiq_OSOCE_NuGet_Tests_UI_Tests_BehaviorFileUploadTests_SampleFilesShouldBeAccessible(browser_-Chrome).zip](https://github.com/Lombiq/UI-Testing-Toolbox/files/13329118/Lombiq_OSOCE_NuGet_Tests_UI_Tests_BehaviorFileUploadTests_SampleFilesShouldBeAccessible.browser_-Chrome.zip)

Perhaps the Shortcuts module doesn't get enabled for some reason? In that case, all tests that require the Shortcuts module failing wouldn't be a surprise (as it seems to happen) because they'll use the same DB snapshot.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-727)

**Comment by Psichorex** [comment]
@Piedone This happens only in the Nuget right? So noone experience failing local builds due to this.

**Comment by Psichorex** [comment]
Also you have attached a dump file. Is that from your local machine? Which branch is it actually from? I am asking because I found something wierd if that dump is coming from one of our OSOE runs:
So the DB snapshot of the failed test doesn't contain an admin user actually which could lead to a 404 exactly where we experience it:
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/92299130/bdedd576-8576-418b-aac0-9aedb408f862)
Here as we know the controller will return 404 if the user is not found and from the Test's log we definitely know that it tried to reach `1/Lombiq.Tests.UI.Shortcuts/Account/SignInDirectly?userName=admin` **USERNAME=ADMIN**

So either the user is the cause or the shortcuts modules not getting enabled is also possible.

**Comment by Piedone** [comment]
I don't have any more examples, but from the ones I added above, yes. The failure dump is from the first linked CI run (attached it just that it doesn't expire if this issue won't be picked up by somebody soon), I haven't seen it happening locally.

I see, I think I know what's going on. Since we don't have that user account defined anywhere, it looks like it's generated [here](https://github.com/Lombiq/Hosting-Tenants/blob/adb4e3f8efb809d06d3d08946b1f188c9e62ffde/Lombiq.Hosting.Tenants.Maintenance/Maintenance/ChangeUserSensitiveContent/ChangeUserSensitiveContentMaintenanceProvider.cs#L72). This is done by [the `ChangeUserSensitiveContent` maintenance](https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.Maintenance/Readme.md#lombiqhostingtenantsmaintenancechangeusersensitivecontent). That shouldn't be active during UI tests, except for its own test.

**Comment by Psichorex** [comment]
Should the `Lombiq.Hosting.Tenants.Maintenance` module be enabled when executing UI tests or it should be turned off?

**Comment by Psichorex** [comment]
Well I ran a UI test locally and stopped it to navigate to the Features menu and check whether the suspicious feature is enabled.
Seems like it is actually enabled.
`Lombiq Hosting - Tenants Maintenance Change User Sensitive Content` is the one that is responsible for the user name conversion if I am not mistaken and I thought that one shouldn't be enabled while UI testing.
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/92299130/9923c773-7dde-49b2-a8e4-8250deff4954)

**Comment by Psichorex** [comment]
I think I found the origin of the bug I will try to describe it in details:

These screenshots are coming from the https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7036541596/job/19149394320 failed build

So in both failed runs the same situation happens:
The test `ChangeUserSensitiveContentMaintenanceTaskShouldBeExecutedSuccessfully` passes.
Then 1 or 2 test passes and neither of them actually use `SignInDirectlyAsync` (BasicOrcahrdFeaturesShouldWork in one run and BasicOrcahrdFeaturesShouldWork and an AzureApplicationInsightsTest in the other run)
Then after these tests the very first test that uses `SignInDirectlyAsync` fails.
This scenario indicates that the appsettings modification from the `ChangeUserSensitiveContentMaintenanceTaskShouldBeExecutedSuccessfully` gets stuck and is being carried on to the other tests which will obviously fail due to this.
As neither of the remaining Hosting.Maintenance features actually has a test in the NuGet I recommend removing the test for the `ChangeUserSensitiveContent` from the NuGet solution and see if we ever come across a flaky build.
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/92299130/2e2ac653-e2e0-4873-ae6e-a3793ed3fbf9)
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/92299130/540aa298-f9b0-4c5b-85a8-84af5a6762cb)
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/92299130/d950a1f1-6393-4dcb-b7dd-9f19c59eee53)

**Comment by Piedone** [comment]
So the problem is that the user account depersonalization will affect all tests, if `ChangeUserSensitiveContentMaintenanceTaskShouldBeExecutedSuccessfully` is the one that happens to run the setup first. You can fix this by running a new setup just for that test. I.e., don't run `ExecuteTestAfterSetupAsync` but `ExecuteTestAsync` with a new setup delegate, not as it is in `UITestBase`.

**Comment by Psichorex** [comment]
So it's not `ChangeUserSensitiveContentMaintenanceTaskShouldBeExecutedSuccessfully` that runs the setup first but upon running `ChangeUserSensitiveContentMaintenanceTaskShouldBeExecutedSuccessfully` every test utilizing `ExecuteTestAfterSetupAsync` will fail after that and only those will pass that don't use `ExecuteTestAfterSetupAsync`.

**Comment by Piedone** [comment]
I see, OK then. The fix is the same though.

**Comment by Piedone** [comment]
This was only an issue in OSOCE, not generally in the UI Testing Toolbox, and was fixed by https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/633.

**Comment by Piedone** [comment]
BTW good catch with the DB!
