### ISSUE TITLE
Basic Orchard features testing should include Workflows and Audit Trail (OSOE-847)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/UI-Testing-Toolbox#363]
Extend `BasicOrchardFeaturesTestingUITestContextExtensions` so it also tests Workflows and Audit Trail.

- Do this similarly to how Media features are tested: a separate extension method just for Workflows, and one for Audit Trail (like `TestMediaOperationsAsync()`). Don't put all the code into the same class though.
- No need to use page classes, just write the test also similar to `TestMediaOperationsAsync()`.
- For Workflows, test the following: Add workflow, add Event and Task, test that workflow runs. You can e.g. display a notification on login or a content item publish.
- For Audit Trail, configure it to record events for a content type, test that content publishing for that type is correctly recorded.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-847)

**Comment by DemeSzabolcs** [comment]
> Extend BasicOrchardFeaturesTestingUITestContextExtensions

> Don't put all the code into the same class though

@Piedone Do you mean to put these new methods in a new `...Extensions` file?

**Comment by Piedone** [comment]
It's up to you how to structure the code, just let's not make that class perpetually longer.

**Comment by DemeSzabolcs** [comment]
What do you think, should we also test the creation itself of the workflow, so clicking trough each step, creating the event and the task, or creating it from a recipe is enough? Then testing the workflow of course.

Because I think clicking it together could be problematic during the part where you have to connect the event with the task: 
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/80963259/ba70dcb9-e328-4504-85df-4f4d4ca7885a)

**Comment by Piedone** [comment]
We need to test that the workflow editor also works, yes, that's why I mentioned adding an Event and a Task. Drag and drop is possible in Selenium, so that step should not be an issue either. See e.g. https://www.browserstack.com/guide/drag-and-drop-in-selenium for inspiration (this is Java, but the API is the same).
